### ISSUE TITLE
Add 'requests' as a dependency

### ISSUE THREAD

**Issue by frewsxcv** [nathan-fiscaletti/ipstackgeo-py#1]
Thanks for writing this library! I just started using it and noticed that it uses the `requests` library, but it's not marked as a dependency in `setup.py`. Should it be added?

**Comment by nathan-fiscaletti** [comment]
Thanks for pointing that out, totally missed that. I'll update it today.

**Comment by nathan-fiscaletti** [comment]
Completed in https://github.com/nathan-fiscaletti/ipstackgeo-py/commit/51aede552bad193ab2d3616d951a750e0affd3c5
